apiVersion: v1
kind: Service
metadata:
  name: webtest-ui
  labels:
    app: webtest-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webtest-ui
